// Run with a jsdom installation available in NODE_PATH.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { createHash, webcrypto } = require('node:crypto');
const { JSDOM } = require('jsdom');
const root = path.resolve(__dirname, '..');
const dom = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'), { url: 'https://example.test/medcanvas/?item=test-flow', runScripts: 'outside-only' });
const w = dom.window;
w.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
w.HTMLDialogElement.prototype.close = function () { this.open = false; };
Object.defineProperty(w.crypto, 'subtle', { value: webcrypto.subtle });
w.URL.createObjectURL = () => 'blob:test'; w.URL.revokeObjectURL = () => {};
let downloadClicks = 0;
w.HTMLAnchorElement.prototype.click = () => { downloadClicks++; };
const bytes = Buffer.from('approved generated bytes for download integrity test');
const sha = createHash('sha256').update(bytes).digest('hex');
const image = { src: `published/assets/test-flow-${sha.slice(0, 12)}.png`, sha256: sha, mimeType: 'image/png', width: 1536, height: 3000, alt: '<script>Not markup</script>' };
const secondSha = 'b'.repeat(64);
const illustrated = { version: 2, kind: 'illustrated-algorithm', slug: 'test-flow', title: 'Algorithm test', subtitle: 'Two reviewed pages', artwork: [image, { ...image, src: `published/assets/test-flow-${secondSha.slice(0, 12)}.webp`, sha256: secondSha, mimeType: 'image/webp', width: 2048, height: 1024 }], sources: [{ label: 'Test source', url: 'https://example.test/source' }] };
const legacy = { version: 1, title: 'Legacy test', sections: [{ heading: 'One', items: ['A'] }, { heading: 'Two', items: ['B'] }] };
const manifest = [{ slug: 'test-flow', data: 'published/test-flow.json' }, { slug: 'legacy', data: 'published/legacy.json' }, { slug: 'bad', data: 'published/bad.json' }];
const docs = { 'published/index.json': manifest, 'published/test-flow.json': illustrated, 'published/legacy.json': legacy, 'published/bad.json': { ...illustrated, slug: 'bad', artwork: [{ ...image, src: 'https://evil.test/image.png' }] } };
w.fetch = async url => {
  const key = String(url).split('?')[0];
  if (key === image.src) return { ok: true, arrayBuffer: async () => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) };
  return { ok: key in docs, json: async () => docs[key] };
};
for (const name of ['renderer.js', 'artwork.js', 'gallery.js']) w.eval(fs.readFileSync(path.join(root, 'js', name), 'utf8'));
(async () => {
  await new Promise(resolve => setTimeout(resolve, 30));
  const art = w.MedCanvas.artwork;
  assert.equal(art.validate(illustrated, 'test-flow'), true);
  for (const src of ['../source.png', 'published/assets/other-123.png', 'data:image/png;base64,AA==', 'https://evil.test/x.png', 'published/assets/test-flow-%2f.png']) {
    assert.equal(art.validate({ ...illustrated, artwork: [{ ...image, src }] }, 'test-flow'), false);
  }
  assert.equal(art.validate({ ...illustrated, artwork: [image, image] }, 'test-flow'), false);
  assert.equal(art.validate({ ...illustrated, artwork: [{ ...image, width: 9000 }] }, 'test-flow'), false);
  assert.equal(art.validate(illustrated, 'other'), false);
  assert.equal(w.document.querySelectorAll('.gallery-card').length, 2, 'invalid graphic is excluded without hiding valid posts');
  assert.equal(w.document.querySelectorAll('#dialog-art img').length, 2, 'all pages displayed');
  assert.equal(w.document.querySelector('#dialog-art img').getAttribute('height'), '3000', 'original aspect ratio retained');
  assert.equal(w.document.querySelectorAll('#dialog-art script').length, 0, 'alt text escaped');
  assert.equal(w.document.querySelector('#download-svg').hidden, true);
  assert.match(w.document.querySelector('#download-png').textContent, /Download image/);
  await art.download(image); assert.equal(downloadClicks, 1);
  await assert.rejects(art.download({ ...image, sha256: '0'.repeat(64) }), /verification failed/);
  w.document.querySelector('[data-slug="legacy"]').click();
  assert.equal(w.document.querySelector('#download-svg').hidden, false);
  assert.equal(w.document.querySelectorAll('#dialog-art svg').length, 1, 'legacy rendering retained');
  w.document.querySelector('[data-slug="test-flow"]').click();
  w.document.querySelector('[data-page="0"]').click();
  await new Promise(resolve => setTimeout(resolve, 30));
  assert.equal(downloadClicks, 2, 'per-page download works');
  console.log('PASS: graphic/legacy gallery, multi-page reader, aspect ratio, safe asset paths, escaped labels, original download and hash mismatch rejection.');
  w.close();
})().catch(error => { console.error(error); w.close(); process.exitCode = 1; });
